# Generated by Django 2.1.5 on 2020-03-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='categoty',
            new_name='category',
        ),
    ]
